### ISSUE TITLE
Work great until 2035, but I want 2040

### ISSUE THREAD

**Issue by lexavey** [Aetherinox/Windows-Update-Killer#1]
![image](https://github.com/user-attachments/assets/59d47cbf-4085-471b-8a6f-ba8bbc255d15)

**Comment by Aetherinox** [comment]
I updated the script.

Updates will pause until 12/31/2051. I don't see any reason to go higher, because typically Microsoft will support updates for 10 years from the time of the last release. By that time we'll know if Windows 12 will be a thing, or if Windows 11 will transform into something else.
