### ISSUE TITLE
Bug: Script does not work on Window 11 and completely disable the window update panel 

### ISSUE THREAD

**Issue by khoalu** [Aetherinox/windows-update-killer#5]
### Description

I try the pause script `windows-updates-pause.reg`, but now it completely disable the update panel, and also auto update when i restart the computer with option "restart computer without update"

Question: how can I bring the window update panel back so i can revert the window update my computer just install automatically ?, I already try the `windows-updates-unpause.reg` and restart without success

### Steps To Reproduce

- On window 11 (with 1 update pending), dont remember which os build / version, also dont have the picture 
- Download the script `windows-updates-pause.reg`
- Double click the script, and run -> get warning from registry editor -> i press yes (i assume the .reg file is to add some register key into my window)
- Open the window update, see it completely disable and different from readme (attached below)
- Restart the computer (with the normal restart, not the "restart and update" on win 11)
- My computer restart and display "your window is updating xx% completed, please keep power up" or something like that, the notification you see every time window update something
- After restart, the window update panel is still disable

### Version

v1.0.4 (latest as the time i write this issue)

### OS / Distro

(after the auto update run) Windows 11 Home Single Language, Version 22H2, OS Build 22621.4317

### Priority

Normal

### Referenced Issues

- #
- #

### Screenshots

![image](https://github.com/user-attachments/assets/6b224f32-8651-4a99-8f4e-cd2510c8dfce)

**Comment by Aetherinox** [comment]
Went through a test setup with mine. Currently running `23H2 - Build 22631.4317`, and both the pause and unpause scripts are working fine for me.

The difficult part here is not having a machine that gives me what you're getting. I'll try to throw up a VM later on 22H2 and see if I can replicate it on there, but if my memory serves me right, 22H2 is where I first started writing this script.

The only difference between our versions is that I'm using Professional instead of Home.

The ONLY thing I could possibly think of, that is causing your interface to glitch like that is maybe an issue with your system not being able to handle all of the options in the dropdown. I forget the number, but it should be trying to pull up / populate roughly 500+ additional entries in the dropdown, which is quite a lot.

Open the pause.reg script, find the line:

```
"FlightSettingsMaxPauseDays"=dword:00002727
```

Change the value to:
```
"FlightSettingsMaxPauseDays"=dword:00000100
```

Then save the file and re-execute it. This will give you a dropdown of 36 weeks, instead of like 800+.

![8wwrOCzaCT](https://github.com/user-attachments/assets/729a85ed-f709-498d-bff6-9e1f2a12be8f)

This will at least confirm if your GUI is just crashing because there's so many options in the dropdown.

**Comment by khoalu** [comment]
The actual script that disable the window update panel was from https://github.com/tsgrgo/windows-update-disabler
After running the script to enable update in above repository and re-executre your script, everything now works fine - updates paused until 2051-12-31.

This issue was error from my part. Sorry for wasting your time.

**Comment by Aetherinox** [comment]
Thanks for letting me know. I'll add a note to the readme. That's sort of why I went with the route I did because I didn't want to start giving users random exe files to execute, and not manipulate the OS.

Glad it works now, enjoy.
